name: Dispatch Release

on:
  release:
    types: [published]

jobs:
  dispatch:
    runs-on: ubuntu-slim
    steps:
      - name: Dispatch to winget-community-pkgs
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: t128n/winget-community-pkgs
          event-type: release
          client-payload: '{"package": "git-wt"}'
